GChatBan: false
ChatFormat:
  setFormat:
    Enable: false
    Format: "Lv.&b{SolarChat.Player.Level} &r| {SolarChat.Player.Prefix} %1$s &aâ–¶&r %2$s"
  CalledEventFormat:
    Enable: true
    Format: "Lv.&b{SolarChat.Player.Level} &r| {SolarChat.Player.Prefix} {SolarChat.Player.Name} &aâ–¶&r {SolarChat.Player.msg}"

Prefix:
  op: "ğŸ‘‘"
  player: "ğŸ "

StopMessage: "[i]"

MySQL:
  Enable: false
  user: "root"
  password: "password"
  host: "localhost"
  port: 3306

YAML:
  Enable: true

Message:
  IPShowEnableWarn: "ä½ ç¡®å®šè¦&b&lå¼€å¯IPåœ°å€æ˜¾ç¤º&rå—ï¼Œè¿™å¯èƒ½ä¼šæ³„éœ²ä½ çš„&b&lä¸ªäººä¿¡æ¯&rå“¦~ ä½¿ç”¨&b&l/show-ip con&ræ¥ç¡®å®šï¼"
  IPShowDisableWarn: "ä½ ç¡®å®šè¦&b&lå…³é—­IPåœ°å€æ˜¾ç¤º&rå—ï¼Œä½¿ç”¨&b&l/show-ip con&ræ¥ç¡®å®šï¼"
  IPShowEnable: "ä½ &b&lå¼€å¯äº†IPåœ°å€å±•ç¤ºåŠŸèƒ½&rå“¦~åœ¨èŠå¤©æ—¶&b&lå°†ä¼šæ˜¾ç¤ºä½ çš„IPåœ°å€å’ŒIPå±åœ°&rï¼å†æ¬¡ä½¿ç”¨&b&l/show-ip conå¯ä»¥å…³é—­&rå“¦~"
  IPShowDisable: "ä½ &b&lå…³é—­äº†IPåœ°å€å±•ç¤ºåŠŸèƒ½&rå“¦~åœ¨èŠå¤©æ—¶&b&lå°†ä¸åœ¨ä¼šæ˜¾ç¤ºä½ çš„IPåœ°å€å’Œæ‰€åœ¨åœ°åŒº&rï¼å†æ¬¡&b&lä½¿ç”¨/show-ip conå¯ä»¥å¼€å¯&rå“¦~"
  IPPEnable: "ä½ æŠŠIPå±åœ°ä¿¡æ¯æ˜¾ç¤ºæ¨¡å¼æ”¹ä¸ºäº†èŠå¤©å‰ç¼€æ¨¡å¼å“¦~"
  IPPDisable: "ä½ æŠŠIPå±åœ°ä¿¡æ¯æ˜¾ç¤ºæ¨¡å¼æ”¹ä¸ºäº†åç§°æ‚¬æµ®çª—æ¨¡å¼å“¦~"
