GChatBan: false
ChatFormat:
  setFormat:
    Enable: false
    Format: "Lv.&b{SolarChat.Player.Level} &r| {SolarChat.Player.Prefix} %1$s &aâ–¶&r %2$s"
  CalledEventFormat:
    Enable: true
    Format: "Lv.&b{SolarChat.Player.Level} &r| {SolarChat.Player.Prefix} {SolarChat.Player.Name} &aâ–¶&r {SolarChat.Player.msg}"

Prefix:
  op: "ğŸ‘‘"
  player: "ğŸ "

StopMessage: "[i]"